language: java
jdk:
 - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: fozitto123